version: "3"
services:
  frontend:
    container_name: frontend_container
    build: frontend
    image: dockerize-quasar-dev
    volumes:
      - /app/node_modules
      - ./frontend/src:/app/src
      - ./frontend/.quasar:/app/.quasar
      - ./frontend/quasar.config.js:/app/quasar.config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - yarfoosball-network

  nginx:
    image: nginx:stable-alpine
    container_name: yarfoosbal-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - yarfoosball-network

networks:
  yarfoosball-network:
    driver: bridge