version: "3"
services:
  db:
    image: huecker.io/library/postgres:14-alpine
    container_name: db_container
    restart: on-failure
    command: -p 6432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env-dev
    expose:
      - 6432
    networks:
      - yarfoosball-network

  pgadmin:
    container_name: pgadmin_container
    image: huecker.io/dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yaroslav.dvoinyh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Cbyufgeh115
    ports:
      - "5050:80"
    networks:
      - yarfoosball-network
    depends_on:
      - db

  backend:
    container_name: backend_container
    build:
      context: ./backend
    command: [ "./docker/app-dev.sh" ]
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    env_file:
      - ./backend/.env-dev
    networks:
      - yarfoosball-network
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend_container
    build: frontend
    image: dockerize-quasar-dev
    volumes:
      - /app/node_modules
      - ./frontend/src:/app/src
      - ./frontend/.quasar:/app/.quasar
      - ./frontend/quasar.config.js:/app/quasar.config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - yarfoosball-network
    depends_on:
      - backend
    ports:
      - "9000:9000"

  nginx:
    image: huecker.io/library/nginx:stable-alpine
    container_name: yarfoosbal-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - yarfoosball-network

networks:
  yarfoosball-network:
    driver: bridge