version: "3"
services:

  nginx:
    image: dockerhub.timeweb.cloud/library/nginx:stable-alpine
    container_name: yarfoosbal-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - yarfoosball-network

  frontend:
    container_name: frontend_container
    build:
      context: frontend
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./frontend/src:/app/src
      - ./frontend/.quasar:/app/.quasar
      - ./frontend/quasar.config.js:/app/quasar.config.js
    env_file:
      - ./.env-dev
    networks:
      - yarfoosball-network
    depends_on:
      - backend
    ports:
      - "9000:9000"

  backend:
    container_name: backend_container
    build:
      context: ./backend
    command: [ "./docker/app-dev.sh" ]
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/kickertool:/app/kickertool
    env_file:
      - ./.env-dev
    networks:
      - yarfoosball-network
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: dockerhub.timeweb.cloud/library/postgres:14-alpine
    container_name: db_container
    restart: on-failure
    command: -p 6432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env-dev
    expose:
      - 6432
    networks:
      - yarfoosball-network

  pgadmin:
    container_name: pgadmin_container
    image: dockerhub.timeweb.cloud/dpage/pgadmin4:7
    restart: always
    env_file:
      - ./.env-dev
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - yarfoosball-network
    depends_on:
      - db

networks:
  yarfoosball-network:
    driver: bridge