version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: yarfoosbal-nginx-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - ./nginx/yarfoosball.ru.crt:/etc/ssl/yarfoosball.ru.crt
      - ./nginx/yarfoosball.ru.key:/etc/ssl/yarfoosball.ru.key
    depends_on:
      - frontend
    networks:
      - yarfoosball-network

  frontend:
    container_name: yarfoosball-frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    networks:
      - yarfoosball-network
    depends_on:
      - backend

  backend:
    container_name: yarfoosball-backend-container
    build:
      context: ./backend
    command: [ "./docker/app.sh" ]
    env_file:
      - ./.env-prod
    networks:
      - yarfoosball-network
    depends_on:
      - db
    # Временно
    ports:
      - "8000:8000"

  db:
    image: postgres:14-alpine
    container_name: yarfoosball-db-container
    restart: on-failure
    command: -p 6432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env-prod
    expose:
      - 6432
    networks:
      - yarfoosball-network

  pgadmin:
    container_name: pgadmin_container
    image: pgadmin4:7
    restart: always
    env_file:
      - ./.env-prod
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - yarfoosball-network
    depends_on:
      - db

networks:
  yarfoosball-network:
    driver: bridge

volumes:
  pgadmin-data: