"""competition-order-nullable

Revision ID: 6e75d05e7116
Revises: 91d2b2277ed9
Create Date: 2024-06-12 16:21:08.611509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e75d05e7116'
down_revision: Union[str, None] = '91d2b2277ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'competition_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'competition_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
