"""add-set-external_id

Revision ID: f0a97092bb5f
Revises: 6e75d05e7116
Create Date: 2024-06-12 17:11:30.988377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a97092bb5f'
down_revision: Union[str, None] = '6e75d05e7116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_sets', sa.Column('external_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_sets', 'external_id')
    # ### end Alembic commands ###
