"""add-external-id-in-all-tables

Revision ID: 21bd65162733
Revises: 8adfaaa90811
Create Date: 2024-06-13 12:30:14.693415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bd65162733'
down_revision: Union[str, None] = '8adfaaa90811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitions', 'external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('leagues', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.alter_column('match_sets', 'external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('matches', 'external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('players', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.alter_column('teams', 'external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('tournament_teams', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.alter_column('tournaments', 'external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('tournament_teams', 'external_id')
    op.alter_column('teams', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('players', 'external_id')
    op.alter_column('matches', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('match_sets', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('leagues', 'external_id')
    op.alter_column('competitions', 'external_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
