"""rename_field_json_data

Revision ID: fa2cf3184a96
Revises: 3be5b96ee095
Create Date: 2024-06-12 10:22:59.616323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa2cf3184a96'
down_revision: Union[str, None] = '3be5b96ee095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('json_data', sa.JSON(), nullable=True))
    op.drop_column('competitions', 'dyp_json')
    op.add_column('match_sets', sa.Column('match_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match_sets', 'matches', ['match_id'], ['id'])
    op.add_column('matches', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'matches', 'competitions', ['competition_id'], ['id'])
    op.add_column('teams', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'competition_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'competition_id')
    op.drop_constraint(None, 'match_sets', type_='foreignkey')
    op.drop_column('match_sets', 'match_id')
    op.add_column('competitions', sa.Column('dyp_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('competitions', 'json_data')
    # ### end Alembic commands ###
