"""add-table-league

Revision ID: f590fd088f40
Revises: 
Create Date: 2024-06-20 07:58:14.396100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f590fd088f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MATCH', 'COMPETITION', name='rating_history_level_enum').create(op.get_bind())
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').create(op.get_bind())
    sa.Enum('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum').create(op.get_bind())
    sa.Enum('DYP', 'TEAM', 'FAST', name='tournament_type_enum').create(op.get_bind())
    op.create_table('leagues',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('type', postgresql.ENUM('DYP', 'TEAM', 'FAST', name='tournament_type_enum', create_type=False), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', postgresql.ENUM('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum', create_type=False), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ratings',
    sa.Column('type', postgresql.ENUM('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum', create_type=False), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_teams',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('competition_order', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('first_player_id', sa.Integer(), nullable=False),
    sa.Column('second_player_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['first_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['second_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('first_team_id', sa.Integer(), nullable=False),
    sa.Column('second_team_id', sa.Integer(), nullable=False),
    sa.Column('is_qualification', sa.Boolean(), nullable=True),
    sa.Column('is_forfeit', sa.Boolean(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['first_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['second_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_sets',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('first_team_score', sa.Integer(), nullable=False),
    sa.Column('second_team_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_history',
    sa.Column('type', postgresql.ENUM('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum', create_type=False), nullable=False),
    sa.Column('level', postgresql.ENUM('MATCH', 'COMPETITION', name='rating_history_level_enum', create_type=False), nullable=False),
    sa.Column('prev_history_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('diff', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['prev_history_id'], ['rating_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_history')
    op.drop_table('match_sets')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('tournament_teams')
    op.drop_table('ratings')
    op.drop_table('competitions')
    op.drop_table('tournaments')
    op.drop_table('players')
    op.drop_table('leagues')
    sa.Enum('DYP', 'TEAM', 'FAST', name='tournament_type_enum').drop(op.get_bind())
    sa.Enum('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum').drop(op.get_bind())
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').drop(op.get_bind())
    sa.Enum('MATCH', 'COMPETITION', name='rating_history_level_enum').drop(op.get_bind())
    # ### end Alembic commands ###
