"""initial

Revision ID: 52883cea49fb
Revises: 
Create Date: 2024-06-05 20:44:37.922043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52883cea49fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').create(op.get_bind())
    sa.Enum('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum').create(op.get_bind())
    sa.Enum('DYP', 'TEAM', 'FAST', name='tournament_type_enum').create(op.get_bind())
    op.create_table('leagues',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('type', postgresql.ENUM('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', postgresql.ENUM('DYP', 'TEAM', 'FAST', name='tournament_type_enum', create_type=False), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', postgresql.ENUM('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum', create_type=False), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitions')
    op.drop_table('tournaments')
    op.drop_table('ratings')
    op.drop_table('players')
    op.drop_table('leagues')
    sa.Enum('DYP', 'TEAM', 'FAST', name='tournament_type_enum').drop(op.get_bind())
    sa.Enum('TEAM', 'DYP', 'OS', 'OD', 'WS', 'WD', 'MS', 'MD', 'AS', 'AD', 'NS', 'ND', 'SPS', 'SPD', 'BS', 'BD', 'JS', 'JD', 'COD', 'MIXED', 'PROAM', name='competition_type_enum').drop(op.get_bind())
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
