"""add-tt-fields

Revision ID: 8adfaaa90811
Revises: 86b236fa8771
Create Date: 2024-06-13 11:57:37.261738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adfaaa90811'
down_revision: Union[str, None] = '86b236fa8771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_id', sa.String(length=30), nullable=True))
    op.add_column('tournaments', sa.Column('json_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'json_data')
    op.drop_column('tournaments', 'external_id')
    # ### end Alembic commands ###
