"""add-last-diff

Revision ID: 8051efae9c40
Revises: e2c754582e9b
Create Date: 2024-06-23 00:06:21.243017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8051efae9c40'
down_revision: Union[str, None] = 'e2c754582e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('last_diff', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'last_diff')
    # ### end Alembic commands ###
