"""add-external_id_field

Revision ID: 9b17c769c2cd
Revises: fa2cf3184a96
Create Date: 2024-06-12 15:14:46.573495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b17c769c2cd'
down_revision: Union[str, None] = 'fa2cf3184a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('external_id', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('external_id', sa.String(length=20), nullable=True))
    op.add_column('teams', sa.Column('external_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'external_id')
    op.drop_column('matches', 'external_id')
    op.drop_column('competitions', 'external_id')
    # ### end Alembic commands ###
