"""rating-history-fields-added

Revision ID: ac1f672f56dd
Revises: ab98e9beee64
Create Date: 2024-07-05 13:42:22.469743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'ac1f672f56dd'
down_revision: Union[str, None] = 'ab98e9beee64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('is_winner', sa.Boolean(), nullable=True))
    op.add_column('rating_history', sa.Column('is_draw', sa.Boolean(), nullable=True))
    op.sync_enum_values('public', 'rating_history_level_enum', ['START', 'MATCH', 'COMPETITION'],
                        [TableReference(table_schema='public', table_name='rating_history', column_name='level')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'rating_history_level_enum', ['MATCH', 'COMPETITION'],
                        [TableReference(table_schema='public', table_name='rating_history', column_name='level')],
                        enum_values_to_rename=[])
    op.drop_column('rating_history', 'is_draw')
    op.drop_column('rating_history', 'is_winner')
    # ### end Alembic commands ###
