"""add-matches-statictic

Revision ID: 8694e0087c9e
Revises: f590fd088f40
Create Date: 2024-06-22 21:42:00.554579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8694e0087c9e'
down_revision: Union[str, None] = 'f590fd088f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('matches', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('matches_diff', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('wins_diff', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('losses_diff', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('matches', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'losses')
    op.drop_column('ratings', 'wins')
    op.drop_column('ratings', 'matches')
    op.drop_column('rating_history', 'losses_diff')
    op.drop_column('rating_history', 'losses')
    op.drop_column('rating_history', 'wins_diff')
    op.drop_column('rating_history', 'wins')
    op.drop_column('rating_history', 'matches_diff')
    op.drop_column('rating_history', 'matches')
    # ### end Alembic commands ###
