"""delete-rating-table

Revision ID: 86b236fa8771
Revises: 5334954311a5
Create Date: 2024-06-12 18:04:36.398807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b236fa8771'
down_revision: Union[str, None] = '5334954311a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum').create(op.get_bind())
    op.create_table('ratings',
    sa.Column('type', postgresql.ENUM('PLAYER', 'LEAGUE', 'TOURNAMENT', name='rating_type_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ratings_pkey')
    )
    # ### end Alembic commands ###
