"""add-rating-competition-id

Revision ID: e2c754582e9b
Revises: 8694e0087c9e
Create Date: 2024-06-22 22:49:31.930810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c754582e9b'
down_revision: Union[str, None] = '8694e0087c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('competition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating_history', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_history', type_='foreignkey')
    op.drop_column('rating_history', 'competition_id')
    # ### end Alembic commands ###
