"""rating-rank-history

Revision ID: f1a1a5326201
Revises: ab8d1079d274
Create Date: 2025-01-31 15:46:29.877991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a1a5326201'
down_revision: Union[str, None] = 'ab8d1079d274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('rank', postgresql.ENUM('beginner', 'novice', 'amateur', 'semipro', 'pro', 'master', name='rank_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_history', 'rank')
    # ### end Alembic commands ###
