"""cumulative-diff

Revision ID: d659acb3d919
Revises: a60eb6e13210
Create Date: 2025-02-02 10:39:11.278295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd659acb3d919'
down_revision: Union[str, None] = 'a60eb6e13210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('cumulative_diff', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_history', 'cumulative_diff')
    # ### end Alembic commands ###
