"""external-id

Revision ID: 282ad7eaa918
Revises: d659acb3d919
Create Date: 2025-04-10 15:05:46.425582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282ad7eaa918'
down_revision: Union[str, None] = 'd659acb3d919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'competitions', ['external_id'])
    op.create_unique_constraint(None, 'leagues', ['external_id'])
    op.create_unique_constraint(None, 'match_sets', ['external_id'])
    op.create_unique_constraint(None, 'matches', ['external_id'])
    op.create_unique_constraint(None, 'players', ['external_id'])
    op.create_unique_constraint(None, 'rating_history', ['external_id'])
    op.create_unique_constraint(None, 'ratings', ['external_id'])
    op.create_unique_constraint(None, 'teams', ['external_id'])
    op.create_unique_constraint(None, 'tournament_teams', ['external_id'])
    op.create_unique_constraint(None, 'tournaments', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_constraint(None, 'tournament_teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_constraint(None, 'rating_history', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_constraint(None, 'match_sets', type_='unique')
    op.drop_constraint(None, 'leagues', type_='unique')
    op.drop_constraint(None, 'competitions', type_='unique')
    # ### end Alembic commands ###
