"""goals-diff

Revision ID: 0a6524601961
Revises: 29360402caee
Create Date: 2025-01-30 20:24:20.065362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6524601961'
down_revision: Union[str, None] = '29360402caee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('tournaments', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('goals', sa.Integer(), nullable=True))
    op.add_column('rating_history', sa.Column('goals_diff', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('tournaments', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('goals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'goals')
    op.drop_column('ratings', 'tournaments')
    op.drop_column('rating_history', 'goals_diff')
    op.drop_column('rating_history', 'goals')
    op.drop_column('rating_history', 'tournaments')
    # ### end Alembic commands ###
