"""rating-rank

Revision ID: ab8d1079d274
Revises: 0a6524601961
Create Date: 2025-01-31 12:42:43.948994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab8d1079d274'
down_revision: Union[str, None] = '0a6524601961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('beginner', 'novice', 'amateur', 'semipro', 'pro', 'master', name='rank_enum').create(op.get_bind())
    op.add_column('ratings', sa.Column('rank', postgresql.ENUM('beginner', 'novice', 'amateur', 'semipro', 'pro', 'master', name='rank_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'rank')
    sa.Enum('beginner', 'novice', 'amateur', 'semipro', 'pro', 'master', name='rank_enum').drop(op.get_bind())
    # ### end Alembic commands ###
