"""cumulative

Revision ID: a60eb6e13210
Revises: f1a1a5326201
Create Date: 2025-02-02 10:30:12.698355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60eb6e13210'
down_revision: Union[str, None] = 'f1a1a5326201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('cumulative', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('cumulative', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'cumulative')
    op.drop_column('rating_history', 'cumulative')
    # ### end Alembic commands ###
